@echo off
rem CamTrap Measure launcher. Double-click to start.
rem
rem Every start first updates the app to REF from the Git remote, then runs it. Offline, or if anything
rem about the update fails, the version already on this computer runs; if the new version's
rem dependencies cannot be installed, the previous version is restored and run. Model weights are not
rem part of this: the app fetches them itself through its weights manifest.
rem
rem Rollback: if a release misbehaves, create a file ref.txt next to this one containing a known-good
rem tag on one line (e.g. v0.1.0), plain text, no spaces. The app stays on that tag at every start until
rem ref.txt is deleted. Do not edit this file for that: Git would refuse to update over a changed file.
rem
rem The update rewrites this very file, and cmd reads a .bat by byte offset while it runs - so everything
rem after the checkout is on the one last line below, which ends by exiting. Keep it that way.
cd /d "%~dp0"
set GIT_TERMINAL_PROMPT=0
set REF=origin/main
if exist ref.txt set /p REF=<ref.txt
for /f %%h in ('git rev-parse HEAD') do set PREV=%%h
git fetch --quiet --tags origin || echo Offline or no remote - running the current version. & git -c advice.detachedHead=false checkout --quiet --detach %REF% || echo Could not switch to %REF% - running the current version. & uv sync --frozen || (echo Dependencies could not be installed - going back to the previous version. & git -c advice.detachedHead=false checkout --quiet --detach %PREV% & uv sync --frozen --offline) & uv run --frozen --offline camtrap-measure || pause & exit /b
